### ISSUE TITLE
Katalon-agent stops after couple of days

### ISSUE THREAD

**Issue by pklinus** [katalon-studio/katalon-agent#22]
Agent Version= 5.0. 

Katalon Agent cannot be run for a long period of time and stops and outputs Invalid/token expired. This makes the agent in an unavailable state (Displayed as grey in Test Ops). To fix, I had to kill the active command line execution and start the execution again. i.e `>cli-win-x64.exe start-agent`  

`[2020-10-05T07:46:03.490] [ERROR] katalon - { status: 401,
  body:
   { error: 'invalid_token',
     error_description:
      'Access token expired: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsia2l0Il0sImV4cCI6MTYwMTM4Mjc4MiwidXNlcl9uYW1lIjoicWFAMjYwMGh6LmNvbSIsImp0aSI6IjY1NzJiNTkyLTg3ODEtNDZkMC04NGVlLWVhMWMwYjdjNWQ4YyIsImNsaWVudF9pZCI6ImtpdF91cGxvYWRlciIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.TVIGB3EvSugJMiO2ezfHrdwNq_N2KW8ckSPVkmK5a1EW7QKl6k6ELVXoo7Xcu-7xvVyegPBJ1CGQqqlmUWNHMlUYIPphYKjRAPcu0lRebigwND0F75P6V6Mklti-XpagmEQHjg-8tLyDQPM9MyVD-gRjFd_XlYpVGKZtcSXYWY1r36XF2n3_b9i6NACSG_gPr63K8aSncvH5DFJt1BXMOqfcwj0w7hto8bf_QzysHrLmBjJUva1PbGlMbXu637eMT97yxx23Svu67wMa_mg_FauKQsGmfDpI4to0U9R4P3ET9NzseZMYpy0VH8NXIzjWOxuw8zb9U8iSsTqnMkpLoQ' } }
[2020-10-05T07:46:03.490] [ERROR] katalon - Cannot send agent info to server: { status: 401,
  body:
   { error: 'invalid_token',
     error_description:
      'Access token expired: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsia2l0Il0sImV4cCI6MTYwMTM4Mjc4MiwidXNlcl9uYW1lIjoicWFAMjYwMGh6LmNvbSIsImp0aSI6IjY1NzJiNTkyLTg3ODEtNDZkMC04NGVlLWVhMWMwYjdjNWQ4YyIsImNsaWVudF9pZCI6ImtpdF91cGxvYWRlciIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.TVIGB3EvSugJMiO2ezfHrdwNq_N2KW8ckSPVkmK5a1EW7QKl6k6ELVXoo7Xcu-7xvVyegPBJ1CGQqqlmUWNHMlUYIPphYKjRAPcu0lRebigwND0F75P6V6Mklti-XpagmEQHjg-8tLyDQPM9MyVD-gRjFd_XlYpVGKZtcSXYWY1r36XF2n3_b9i6NACSG_gPr63K8aSncvH5DFJt1BXMOqfcwj0w7hto8bf_QzysHrLmBjJUva1PbGlMbXu637eMT97yxx23Svu67wMa_mg_FauKQsGmfDpI4to0U9R4P3ET9NzseZMYpy0VH8NXIzjWOxuw8zb9U8iSsTqnMkpLoQ' } }
[2020-10-05T07:46:03.506] [INFO] katalon - PATCH https://analytics.katalon.com/api/v1/jobs/145183 401.
[2020-10-05T07:46:03.506] [ERROR] katalon - { status: 401,
  body:
   { error: 'invalid_token',
     error_description:
      'Access token expired: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsia2l0Il0sImV4cCI6MTYwMTM4Mjc4MiwidXNlcl9uYW1lIjoicWFAMjYwMGh6LmNvbSIsImp0aSI6IjY1NzJiNTkyLTg3ODEtNDZkMC04NGVlLWVhMWMwYjdjNWQ4YyIsImNsaWVudF9pZCI6ImtpdF91cGxvYWRlciIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.TVIGB3EvSugJMiO2ezfHrdwNq_N2KW8ckSPVkmK5a1EW7QKl6k6ELVXoo7Xcu-7xvVyegPBJ1CGQqqlmUWNHMlUYIPphYKjRAPcu0lRebigwND0F75P6V6Mklti-XpagmEQHjg-8tLyDQPM9MyVD-gRjFd_XlYpVGKZtcSXYWY1r36XF2n3_b9i6NACSG_gPr63K8aSncvH5DFJt1BXMOqfcwj0w7hto8bf_QzysHrLmBjJUva1PbGlMbXu637eMT97yxx23Svu67wMa_mg_FauKQsGmfDpI4to0U9R4P3ET9NzseZMYpy0VH8NXIzjWOxuw8zb9U8iSsTqnMkpLoQ' } }
[2020-10-05T07:46:03.506] [INFO] katalon - PATCH https://analytics.katalon.com/api/v1/jobs/144112 401.
[2020-10-05T07:46:03.506] [ERROR] katalon - { status: 401,
  body:
   { error: 'invalid_token',
     error_description:
      'Access token expired: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsia2l0Il0sImV4cCI6MTYwMTM4Mjc4MiwidXNlcl9uYW1lIjoicWFAMjYwMGh6LmNvbSIsImp0aSI6IjY1NzJiNTkyLTg3ODEtNDZkMC04NGVlLWVhMWMwYjdjNWQ4YyIsImNsaWVudF9pZCI6ImtpdF91cGxvYWRlciIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.TVIGB3EvSugJMiO2ezfHrdwNq_N2KW8ckSPVkmK5a1EW7QKl6k6ELVXoo7Xcu-7xvVyegPBJ1CGQqqlmUWNHMlUYIPphYKjRAPcu0lRebigwND0F75P6V6Mklti-XpagmEQHjg-8tLyDQPM9MyVD-gRjFd_XlYpVGKZtcSXYWY1r36XF2n3_b9i6NACSG_gPr63K8aSncvH5DFJt1BXMOqfcwj0w7hto8bf_QzysHrLmBjJUva1PbGlMbXu637eMT97yxx23Svu67wMa_mg_FauKQsGmfDpI4to0U9R4P3ET9NzseZMYpy0VH8NXIzjWOxuw8zb9U8iSsTqnMkpLoQ' } }
[2020-10-05T07:46:03.506] [INFO] katalon - PATCH https://analytics.katalon.com/api/v1/jobs/145294 401.
[2020-10-05T07:46:03.506] [ERROR] katalon - { status: 401,
  body:
   { error: 'invalid_token',
     error_description:
      'Access token expired: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsia2l0Il0sImV4cCI6MTYwMTM4Mjc4MiwidXNlcl9uYW1lIjoicWFAMjYwMGh6LmNvbSIsImp0aSI6IjY1NzJiNTkyLTg3ODEtNDZkMC04NGVlLWVhMWMwYjdjNWQ4YyIsImNsaWVudF9pZCI6ImtpdF91cGxvYWRlciIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.TVIGB3EvSugJMiO2ezfHrdwNq_N2KW8ckSPVkmK5a1EW7QKl6k6ELVXoo7Xcu-7xvVyegPBJ1CGQqqlmUWNHMlUYIPphYKjRAPcu0lRebigwND0F75P6V6Mklti-XpagmEQHjg-8tLyDQPM9MyVD-gRjFd_XlYpVGKZtcSXYWY1r36XF2n3_b9i6NACSG_gPr63K8aSncvH5DFJt1BXMOqfcwj0w7hto8bf_QzysHrLmBjJUva1PbGlMbXu637eMT97yxx23Svu67wMa_mg_FauKQsGmfDpI4to0U9R4P3ET9NzseZMYpy0VH8NXIzjWOxuw8zb9U8iSsTqnMkpLoQ' } }
[2020-10-05T07:46:03.615] [INFO] katalon - post https://analytics.katalon.com/oauth/token 500.
[2020-10-05T07:46:03.615] [ERROR] katalon - { status: 500,
  body:`

**Comment by thongmgnguyen** [comment]
Hi @pklinus ,
We released a fixed version 1.5.1. Please download the new version and try again.
Thanks,
Thong.

**Comment by pklinus** [comment]
Thanks @thongmgnguyen
